### A Pluto.jl notebook ###
# v0.9.4

using Markdown

# ╔═╡ d6491e5e-a842-11ea-07a2-e53bd9da16fc
md"""
## Trying out Pluto.jl with Project Euler

Each new term in the Fibonacci sequence is generated by adding the *previous* two terms. By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the **even-valued** terms. 
"""

# ╔═╡ 4145dce2-a843-11ea-3b48-f5c4abe5fa69
limit = 4000000

# ╔═╡ fdd6a46e-a842-11ea-0cae-e94b7bcc5ed4
begin
	total = 0
	prev = 0 
	curr = 1
	while curr ≤ limit
		if curr % 2 == 0
			global total += curr
		end
		global prev, curr = curr, prev + curr
	end
	total
end

# ╔═╡ 59ff90c0-a843-11ea-3d95-4d1bd1cfb448
prev

# ╔═╡ Cell order:
# ╟─d6491e5e-a842-11ea-07a2-e53bd9da16fc
# ╠═4145dce2-a843-11ea-3b48-f5c4abe5fa69
# ╠═fdd6a46e-a842-11ea-0cae-e94b7bcc5ed4
# ╠═59ff90c0-a843-11ea-3d95-4d1bd1cfb448
